### ISSUE TITLE
ABSOLUTE PATH ISSUE

### ISSUE THREAD

**Issue by dariopasquali** [ishuah91/nella#1]
Ti sembra normale mettere tutte i path in forma assoluta??? Non puoi pubblicare un progetto di questo tipo! non funziona nulla. Inoltre il tutto muore quando cerco di iniziare la partita, non carica le immagini e di conseguenza non mi permette di fare nulla.

---

Does it seem normal to put all the path in absolute form ??? You can not publish a project of this kind! nothing works. Moreover everything dies when I try to start the game, not loads images and therefore will not let me do anything.

![untitled](https://cloud.githubusercontent.com/assets/11158169/14637547/4b3efe20-0632-11e6-91d4-895d01be3b1e.png)

**Comment by ishuah** [comment]
@dariopasquali I imported this project from source forge and I'm currently working on bringing it up to speed. Sorry for the inconvenience.
